version: '3.9'

services:
  postgres_db:
    image: postgres:16.0-alpine
    container_name: app_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 3s
      timeout: 5s
      retries: 10
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '1234'
    ports:
      - 5444:5432
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: